export const LOCATIONS = [
  {
    name: "Crusader",
    children: [
      "Crusader",
      "Cellin",
      "Yela",
      "Grim Hex",
      "Daymar",
      "CRU-L1",
      "CRU-L2",
      "CRU-L3",
      "CRU-L4",
      "CRU-L5",
    ],
  },
  {
    name: "Hurston",
    children: [
      "Hurston",
      "Ita",
      "Aberdeen",
      "Arial",
      "Magda",
      "HUR-L1",
      "HUR-L2",
      "HUR-L3",
      "HUR-L4",
      "HUR-L5",
    ],
  },
  {
    name: "ArCorp",
    children: [
      "ArCorp",
      "Wala",
      "Lyria",
      "ARC-L1",
      "ARC-L2",
      "ARC-L3",
      "ARC-L4",
      "ARC-L5",
    ],
  },
  {
    name: "Microtech",
    children: [
      "Microtech",
      "Calliope",
      "Clio",
      "Euterpe",
      "MIC-L1",
      "MIC-L2",
      "MIC-L3",
      "MIC-L4",
      "MIC-L5",
    ],
  },
  { name: "Stanton", children: ["Aaron Halo", "Stanton"] },
];
